[package]
name = "urma-wallet"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
readme = false
include = ["Cargo.toml", "src/**/*.rs"]
description = "URMA wallet funding, addresses and transaction signing"

[dependencies]
bitcoin = "0.32"
serde = { version = "1", features = ["derive"] }
urma-core = { version = "0.2.0", path = "../urma-core" }
urma-chain = { version = "0.2.0", path = "../urma-chain" }
urma-identity = { version = "0.2.0", path = "../urma-identity" }
bech32 = "0.11"
